name: jigajoga

services:
  game-srv:
    build:
      context: .
      dockerfile: svc/game-srv/Dockerfile
    ports:
      - "8080:8081"

  redis:
    image: "redis/redis-stack-server:7.2.0-v11"
    ports:
      - "6379:6379"
